parameter:
  lr: 2e-5
  round: 10
  num_users: 3
  frac: 0.7

path:
  models_save_path: 'models/'
  job_path: 'fl_job_config'

server:
  ip: '127.0.0.1'
  port: '8181'

scheduler:
  ip: '127.0.0.1'
  port: '9091'