parameter:
  lr: 1e-2
  epochs: 3
  bs: 1
  round: 5
  model: 'mlp'

show:
  loss: True
  contribution: True

path:
  output_path: 'fl_model/'
  job_path: 'fl_job_config/'
  data_path: 'data/data/'

test:
  thresholds: 0.2

server:
  ip: '127.0.0.1'
  port: '8181'

scheduler:
  ip: '127.0.0.1'
  port: '9091'

client:
  ip: '127.0.0.1'
  port: '8182'